const express = require('express');
const router = express.Router();
const validUrl = require('valid-url');
const shortid = require('shortid');
const config = require('config');
const crypto = require('crypto');
const Url = require('../models/url');
const base62 = require('base62');

// Basic Auth Middleware
const basicAuth = (req, res, next) => {
    const authHeader = req.headers.authorization;
    if (!authHeader) {
        res.setHeader('WWW-Authenticate', 'Basic realm="Robovitics Admin"');
        return res.status(401).json({ error: 'Authentication required' });
    }

    const parts = authHeader.split(' ');
    if (parts.length !== 2 || parts[0].toLowerCase() !== 'basic') {
        res.setHeader('WWW-Authenticate', 'Basic realm="Robovitics Admin"');
        return res.status(401).json({ error: 'Authentication required' });
    }

    const token = parts[1];
    try {
        const credentials = Buffer.from(token, 'base64').toString('ascii').split(':');
        const username = credentials[0];
        const password = credentials[1];

        const expectedUsername = config.get('adminUsername') || 'admin';
        const expectedPassword = config.get('adminPassword') || 'roboviticsadmin';

        if (username === expectedUsername && password === expectedPassword) {
            return next();
        }
    } catch (err) {
        // Fall through
    }

    res.setHeader('WWW-Authenticate', 'Basic realm="Robovitics Admin"');
    return res.status(401).json({ error: 'Invalid credentials' });
};

//@route post /api/url/shorten
//@desc create short url
router.post('/shorten', async (req, res) => {
    const { longUrl } = req.body;
    const baseURL = config.get('baseURL');

    if (!validUrl.isUri(baseURL)) {
        return res.status(401).json('Invalid URL entered')
    }

    //GENERATing CUSTOM UR....I WILL CREATE A HASH USING MD5 AND THEN USE BASE62 TO GET THE SHORT ID (62 CHARACTERS)
    const generateUrlCode = (longUrl) => {
        const buffer = crypto.createHash('md5').update(longUrl).digest();

        return buffer.subarray(0, 4).toString('base64url');
    };

    if (validUrl.isUri(longUrl)) {
        try {
            let url = await Url.findOne({ longUrl });
            if (url) {
                res.json(url);
            }
            else {
                let urlCode = generateUrlCode(longUrl);
                let urlExists = await Url.findOne({ urlCode });

                // If collision occurs, appending a random number as suffix to ensure uniquenss
                while (urlExists) {
                    const randomSuffix = Math.floor(Math.random() * 1000000).toString();
                    urlCode = generateUrlCode(longUrl + randomSuffix);
                    urlExists = await Url.findOne({ urlCode });
                }

                const shortUrl = baseURL + '/' + urlCode;
                url = new Url({
                    longUrl,
                    shortUrl,
                    urlCode,
                    date: new Date()
                });

                await url.save();
                res.json(url);
            }
        }
        catch (err) {
            console.error(err);
            res.status(500).json('Server Error');
        }
    }
    else {
        res.status(401).json('INVALID URL ENTERED');
    }
});

// Admin Route: Get all custom links generated by the admin
router.get('/admin/links', basicAuth, async (req, res) => {
    try {
        const urls = await Url.find({ isAdminGenerated: true }).sort({ date: -1 });
        res.json(urls);
    } catch (err) {
        console.error(err);
        res.status(500).json('Server Error');
    }
});

// Admin Route: Create or Overwrite custom URL
router.post('/admin/custom-shorten', basicAuth, async (req, res) => {
    const { longUrl, customCode } = req.body;
    const baseURL = config.get('baseURL');

    if (!validUrl.isUri(baseURL)) {
        return res.status(500).json('Invalid base URL config');
    }

    if (!customCode || customCode.trim().length === 0) {
        return res.status(400).json('Custom code is required');
    }

    const cleanCode = customCode.trim().toLowerCase();

    if (!validUrl.isUri(longUrl)) {
        return res.status(400).json('INVALID URL ENTERED');
    }

    try {
        let url = await Url.findOne({ urlCode: cleanCode });
        const shortUrl = baseURL + '/' + cleanCode;
        
        if (url) {
            // Overwrite existing custom URL
            url.longUrl = longUrl;
            url.shortUrl = shortUrl;
            url.isAdminGenerated = true;
            url.date = new Date();
            await url.save();
            res.json(url);
        } else {
            // Create new custom URL
            url = new Url({
                longUrl,
                shortUrl,
                urlCode: cleanCode,
                isAdminGenerated: true,
                date: new Date()
            });
            await url.save();
            res.json(url);
        }
    } catch (err) {
        console.error(err);
        res.status(500).json('Server Error');
    }
});

// Admin Route: Update link destination URL
router.put('/admin/links/:code', basicAuth, async (req, res) => {
    const { longUrl } = req.body;
    const code = req.params.code.trim().toLowerCase();

    if (!validUrl.isUri(longUrl)) {
        return res.status(400).json('INVALID URL ENTERED');
    }

    try {
        let url = await Url.findOne({ urlCode: code });
        if (!url) {
            return res.status(404).json('URL not found');
        }

        // Only allow modifying admin generated links
        if (!url.isAdminGenerated) {
            return res.status(403).json('Cannot modify public links');
        }

        url.longUrl = longUrl;
        url.date = new Date();
        await url.save();
        res.json(url);
    } catch (err) {
        console.error(err);
        res.status(500).json('Server Error');
    }
});

// Admin Route: Delete link
router.delete('/admin/links/:code', basicAuth, async (req, res) => {
    const code = req.params.code.trim().toLowerCase();
    try {
        const url = await Url.findOne({ urlCode: code });
        if (!url) {
            return res.status(404).json('URL not found');
        }

        // Only allow deleting admin generated links
        if (!url.isAdminGenerated) {
            return res.status(403).json('Cannot delete public links');
        }

        await Url.deleteOne({ urlCode: code });
        res.json({ message: 'URL deleted successfully' });
    } catch (err) {
        console.error(err);
        res.status(500).json('Server Error');
    }
});

router.basicAuth = basicAuth;

module.exports = router;
